language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: test
      script: ./gradlew test --scan -s
    - stage: build
      script: ./gradlew bootWar --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/